#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
feh --bg-fill image/background/08082.png &
polybar &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color '#ff0055'
bspc config normal_border_color '#000000';

bspc config split_ratio 0.52

bspc config borderless_monocle true
bspc config gapless_monocle true
